Replace deprecated update_attributes! with update!
The `update_attributes*` methods have been soft deprecated
since 2013 and hard deprecated in Rails 6.1:
NoMethodError: undefined method `update_attributes!'

The `update` and `update!` methods should be used instead.